name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit:
    name: Unit (${{ matrix.service }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [auth, product, order, api-gateway]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: |
            package-lock.json
            auth/package-lock.json
            product/package-lock.json
            order/package-lock.json
            api-gateway/package-lock.json

      - name: Install dependencies
        working-directory: ${{ matrix.service }}
        run: npm ci

      - name: Lint (optional)
        working-directory: ${{ matrix.service }}
        shell: bash
        run: |
          if node -e "process.exit(!((require('./package.json').scripts||{}).lint))"; then
            echo '✅ Found "lint" script. Running...'
            npm run lint
          else
            echo '⚠️  No "lint" script. Skipping.'
          fi

      - name: Run unit tests (infra-safe)
        working-directory: ${{ matrix.service }}
        shell: bash
        env:
          INTEGRATION: "0"
        run: |
          if node -e "process.exit(!((require('./package.json').scripts||{}).test))"; then
            echo '✅ Found "test" script. Running...'
            npm test
          else
            echo '⚠️  No "test" script. Skipping.'
          fi
